name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.1.7

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4.0.0

      - name: "Setup node"
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run Build"
        run: pnpm run build

      - name: "Upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*
