name: "Publish"

on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2

      - name: "Update version"
        run: |
          echo $(jq '.version="${{ github.event.release.tag_name }}"' package.json) > package.json

      - name: "Extract engines"
        id: engines
        run: echo ::set-output name=node::$(jq --raw-output .engines.node ./package.json)

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v2

      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.engines.outputs.node }}
          cache: ${{ !env.ACT && 'pnpm' || '' }}

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run Build"
        run: pnpm run build

      - name: "Upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*
